const LoginPage = require("../pageobjects/login.page");
const InventoryPage = require("../pageobjects/inventory.page");
const CartPage = require("../pageobjects/cart.page");
const CheckoutPage = require("../pageobjects/checkout.page");
const OverviewPage = require("../pageobjects/overview.page");
const CheckoutCompletePage = require("../pageobjects/checkoutComplete.page");

describe("e2e", () => {
  it("Valid checkout with standard_user", async () => {
    await LoginPage.open();
    await LoginPage.fillOutInputs("standard_user", "secret_sauce");
    await LoginPage.login();
    await InventoryPage.addToCart(1);
    await InventoryPage.verifyCartBage("yes", 1);
    const selectedItemName = await InventoryPage.getSelectedItemName();
    const selectedItemPrice = await InventoryPage.getSelectedItemPrice();
    await InventoryPage.getToCart();
    await CartPage.verifyItemsInCart(selectedItemName);
    await CartPage.openCheckoutForm();
    await CheckoutPage.fillOutTheForm("Dmytro", "Reva", 25009);
    await CheckoutPage.submitForm();
    await OverviewPage.verifyItemsInOverview(selectedItemName);
    await OverviewPage.checkSubTotalPrice(selectedItemPrice);
    await OverviewPage.finishCheckout();
    await CheckoutCompletePage.verifyCheckoutCompleteTitle();
    await CheckoutCompletePage.getBackToInventoryPage();
    await InventoryPage.verifyCartBage();
  });
  it("Valid checkout with locked_out_user", async () => {
    await LoginPage.open();
    await LoginPage.fillOutInputs("locked_out_user", "secret_sauce");
    await LoginPage.login();
    await InventoryPage.addToCart(1);
    await InventoryPage.verifyCartBage("yes", 1);
    const selectedItemName = await InventoryPage.getSelectedItemName();
    const selectedItemPrice = await InventoryPage.getSelectedItemPrice();
    await InventoryPage.getToCart();
    await CartPage.verifyItemsInCart(selectedItemName);
    await CartPage.openCheckoutForm();
    await CheckoutPage.fillOutTheForm("Dmytro", "Reva", 25009);
    await CheckoutPage.submitForm();
    await OverviewPage.verifyItemsInOverview(selectedItemName);
    await OverviewPage.checkSubTotalPrice(selectedItemPrice);
    await OverviewPage.finishCheckout();
    await CheckoutCompletePage.verifyCheckoutCompleteTitle();
    await CheckoutCompletePage.getBackToInventoryPage();
    await InventoryPage.verifyCartBage();
  });
  it("Valid checkout with problem_user", async () => {
    await LoginPage.open();
    await LoginPage.fillOutInputs("problem_user", "secret_sauce");
    await LoginPage.login();
    await InventoryPage.addToCart(1);
    await InventoryPage.verifyCartBage("yes", 1);
    const selectedItemName = await InventoryPage.getSelectedItemName();
    const selectedItemPrice = await InventoryPage.getSelectedItemPrice();
    await InventoryPage.getToCart();
    await CartPage.verifyItemsInCart(selectedItemName);
    await CartPage.openCheckoutForm();
    await CheckoutPage.fillOutTheForm("Dmytro", "Reva", 25009);
    await CheckoutPage.submitForm();
    await OverviewPage.verifyItemsInOverview(selectedItemName);
    await OverviewPage.checkSubTotalPrice(selectedItemPrice);
    await OverviewPage.finishCheckout();
    await CheckoutCompletePage.verifyCheckoutCompleteTitle();
    await CheckoutCompletePage.getBackToInventoryPage();
    await InventoryPage.verifyCartBage();
  });
  it("Valid checkout with performance_glitch_user", async () => {
    await LoginPage.open();
    await LoginPage.fillOutInputs("performance_glitch_user", "secret_sauce");
    await LoginPage.login();
    await InventoryPage.addToCart(1);
    await InventoryPage.verifyCartBage("yes", 1);
    const selectedItemName = await InventoryPage.getSelectedItemName();
    const selectedItemPrice = await InventoryPage.getSelectedItemPrice();
    await InventoryPage.getToCart();
    await CartPage.verifyItemsInCart(selectedItemName);
    await CartPage.openCheckoutForm();
    await CheckoutPage.fillOutTheForm("Dmytro", "Reva", 25009);
    await CheckoutPage.submitForm();
    await OverviewPage.verifyItemsInOverview(selectedItemName);
    await OverviewPage.checkSubTotalPrice(selectedItemPrice);
    await OverviewPage.finishCheckout();
    await CheckoutCompletePage.verifyCheckoutCompleteTitle();
    await CheckoutCompletePage.getBackToInventoryPage();
    await InventoryPage.verifyCartBage();
  });
  it("Valid checkout with error_user", async () => {
    await LoginPage.open();
    await LoginPage.fillOutInputs("error_user", "secret_sauce");
    await LoginPage.login();
    await InventoryPage.addToCart(1);
    await InventoryPage.verifyCartBage("yes", 1);
    const selectedItemName = await InventoryPage.getSelectedItemName();
    const selectedItemPrice = await InventoryPage.getSelectedItemPrice();
    await InventoryPage.getToCart();
    await CartPage.verifyItemsInCart(selectedItemName);
    await CartPage.openCheckoutForm();
    await CheckoutPage.fillOutTheForm("Dmytro", "Reva", 25009);
    await CheckoutPage.submitForm();
    await OverviewPage.verifyItemsInOverview(selectedItemName);
    await OverviewPage.checkSubTotalPrice(selectedItemPrice);
    await OverviewPage.finishCheckout();
    await CheckoutCompletePage.verifyCheckoutCompleteTitle();
    await CheckoutCompletePage.getBackToInventoryPage();
    await InventoryPage.verifyCartBage();
  });
  it("Valid checkout with visual_user", async () => {
    await LoginPage.open();
    await LoginPage.fillOutInputs("visual_user", "secret_sauce");
    await LoginPage.login();
    await InventoryPage.addToCart(1);
    await InventoryPage.verifyCartBage("yes", 1);
    const selectedItemName = await InventoryPage.getSelectedItemName();
    const selectedItemPrice = await InventoryPage.getSelectedItemPrice();
    await InventoryPage.getToCart();
    await CartPage.verifyItemsInCart(selectedItemName);
    await CartPage.openCheckoutForm();
    await CheckoutPage.fillOutTheForm("Dmytro", "Reva", 25009);
    await CheckoutPage.submitForm();
    await OverviewPage.verifyItemsInOverview(selectedItemName);
    await OverviewPage.checkSubTotalPrice(selectedItemPrice);
    await OverviewPage.finishCheckout();
    await CheckoutCompletePage.verifyCheckoutCompleteTitle();
    await CheckoutCompletePage.getBackToInventoryPage();
    await InventoryPage.verifyCartBage();
  });
});
